apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflows-full-access-binding
subjects:
  - kind: ServiceAccount
    name: argo-service-account
    namespace: argo
roleRef:
  kind: ClusterRole
  name: argo-workflows-full-access
  apiGroup: rbac.authorization.k8s.io
